env:
  global:
    - CC_TEST_REPORTER_ID=eb2b2a3e52ab654ab2d807c78afa65a5c3b435b782f2f02cd3a4edaf8ff14475

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - go vet ./...

after_script:
  - ./cc-test-reporter after-build --coverage-input-type gocov --exit-code $TRAVIS_TEST_RESULT

language: go

go:
  - "1.9"

script:
  - go test github.com/danidee10/go-rave/rave -v 2
  - go test github.com/danidee10/go-rave/tests -v 2 -coverprofile=cover.out